# Generated by Django 6.0.2 on 2026-02-20 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ciclo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Laboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(blank=True, max_length=150, null=True)),
                ('estado', models.CharField(choices=[('ACTIVO', 'ACTIVO'), ('INACTIVO', 'INACTIVO'), ('EN MANTENIMIENTO', 'EN MANTENIMIENTO')], default='ACTIVO', max_length=20)),
                ('responsable', models.CharField(max_length=100)),
                ('correo_responsable', models.CharField(default='innovacion@ucacue.edu.ec', max_length=100)),
                ('numero_responsable', models.CharField(blank=True, max_length=100, null=True)),
                ('capacidad', models.IntegerField(default=15)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='laboratorios/')),
            ],
        ),
        migrations.CreateModel(
            name='Paralelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('tipo', models.CharField(choices=[('HABIL', 'HABIL'), ('BLOQUEADA', 'BLOQUEADA')], default='HABIL', max_length=20)),
            ],
            options={
                'ordering': ['hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Estacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('modelo', models.CharField(blank=True, max_length=50, null=True)),
                ('estado', models.CharField(choices=[('ACTIVO', 'ACTIVO'), ('INACTIVO', 'INACTIVO'), ('SUSPENDIDO', 'SUSPENDIDO')], default='ACTIVO', max_length=20)),
                ('laboratorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estaciones', to='core.laboratorio')),
            ],
        ),
        migrations.CreateModel(
            name='EstacionPrograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estaciones', to='core.estacion')),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programas', to='core.programa')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('estado', models.CharField(choices=[('APROBADA', 'APROBADA'), ('EN REVISION', 'EN REVISION'), ('CANCELADA', 'CANCELADA'), ('FINALIZADA', 'FINALIZADA'), ('BLOQUEADA', 'BLOQUEADA'), ('ESTUDIANTIL', 'ESTUDIANTIL')], default='EN REVISION', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('asignatura', models.CharField(blank=True, max_length=200, null=True)),
                ('grupo', models.IntegerField(default=1)),
                ('estudiantes', models.IntegerField(default=1)),
                ('tipo', models.CharField(choices=[('INDUCCION DOCENTE', 'INDUCCION DOCENTE'), ('INDUCCION ESTUDIANTIL', 'INDUCCION ESTUDIANTIL'), ('CLASES NORMALES', 'CLASES NORMALES')], default='CLASES NORMALES', max_length=30)),
                ('carrera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.carrera')),
                ('ciclo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.ciclo')),
                ('estacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.estacion')),
                ('laboratorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.laboratorio')),
                ('paralelo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.paralelo')),
            ],
        ),
    ]
