# Generated by Django 6.0.2 on 2026-02-10 21:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Laboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(blank=True, max_length=150, null=True)),
                ('estado', models.CharField(default='ACTIVO', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Estacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('estado', models.CharField(default='ACTIVO', max_length=20)),
                ('laboratorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estaciones', to='core.laboratorio')),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
            ],
            options={
                'ordering': ['hora_inicio'],
                'unique_together': {('hora_inicio', 'hora_fin')},
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('CANCELADA', 'Cancelada'), ('FINALIZADA', 'Finalizada')], default='ACTIVA', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.estacion')),
                ('laboratorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.laboratorio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.timeslot')),
            ],
            options={
                'indexes': [models.Index(fields=['laboratorio', 'fecha', 'slot'], name='core_reserv_laborat_cc9fc9_idx'), models.Index(fields=['estacion', 'fecha', 'slot'], name='core_reserv_estacio_3ac2c0_idx')],
            },
        ),
    ]
