# Generated by Django 6.0.2 on 2026-02-11 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='laboratorio',
            name='capacidad',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='laboratorio',
            name='responsable',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timeslot',
            name='tipo',
            field=models.CharField(choices=[('HABIL', 'HABIL'), ('BLOQUEADA', 'BLOQUEADA')], default='HABIL', max_length=20),
        ),
        migrations.AlterField(
            model_name='estacion',
            name='estado',
            field=models.CharField(choices=[('ACTIVO', 'ACTIVO'), ('INACTIVO', 'INACTIVO'), ('SUSPENDIDO', 'SUSPENDIDO')], default='ACTIVO', max_length=20),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('ACTIVA', 'ACTIVA'), ('CANCELADA', 'CANCELADA'), ('FINALIZADA', 'FINALIZADA')], default='ACTIVA', max_length=20),
        ),
        migrations.CreateModel(
            name='EstacionPrograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estaciones', to='core.estacion')),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programas', to='core.programa')),
            ],
        ),
    ]
