# Generated by Django 6.0.2 on 2026-02-20 17:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='timeslot',
            unique_together={('hora_inicio', 'hora_fin')},
        ),
        migrations.AddField(
            model_name='reserva',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.timeslot'),
        ),
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['laboratorio', 'fecha', 'slot'], name='core_reserv_laborat_cc9fc9_idx'),
        ),
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['estacion', 'fecha', 'slot'], name='core_reserv_estacio_3ac2c0_idx'),
        ),
    ]
