# Generated by Django 6.0.2 on 2026-02-23 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estacionprograma',
            name='estacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estacion_programas', to='core.estacion'),
        ),
        migrations.AlterField(
            model_name='estacionprograma',
            name='programa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programa_estaciones', to='core.programa'),
        ),
    ]
