# Generated by Django 6.0.2 on 2026-02-11 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_carrera_ciclo_paralelo_reserva_asignatura_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratorio',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='laboratorios/'),
        ),
    ]
