# Generated by Django 6.0.2 on 2026-02-26 15:56

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_parametro_correo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenLaboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to=core.models.laboratorio_upload_path)),
                ('laboratorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='core.laboratorio')),
            ],
        ),
    ]
