# Generated by Django 6.0.2 on 2026-02-12 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_laboratorio_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratorio',
            name='estado',
            field=models.CharField(choices=[('ACTIVO', 'ACTIVO'), ('INACTIVO', 'INACTIVO'), ('EN MANTENIMIENTO', 'EN MANTENIMIENTO')], default='ACTIVO', max_length=20),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('ACTIVA', 'ACTIVA'), ('EN REVISION', 'EN REVISION'), ('CANCELADA', 'CANCELADA'), ('FINALIZADA', 'FINALIZADA')], default='ACTIVA', max_length=20),
        ),
    ]
