# Generated by Django 6.0.2 on 2026-02-27 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_imagenlaboratorio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(default='Sin Codigo', max_length=20)),
                ('serie', models.CharField(default='Sin S/N', max_length=50)),
                ('marca', models.CharField(blank=True, max_length=100, null=True)),
                ('modelo', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo', models.CharField(blank=True, max_length=100, null=True)),
                ('detalles', models.CharField(blank=True, max_length=200, null=True)),
                ('estado', models.CharField(choices=[('NUEVO', 'NUEVO'), ('CORRECTO', 'CORRECTO'), ('PENDIENTE', 'PENDIENTE'), ('MANTENIMIENTO', 'MANTENIMIENTO'), ('FALLANDO', 'FALLANDO'), ('BAJA', 'BAJA')], default='PENDIENTE', max_length=20)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('laboratorio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.laboratorio')),
            ],
        ),
    ]
