# Generated by Django 6.0.2 on 2026-02-12 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_laboratorio_estado_alter_reserva_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='tipo',
            field=models.CharField(choices=[('ACTIVA', 'ACTIVA'), ('EN REVISION', 'EN REVISION'), ('CANCELADA', 'CANCELADA'), ('FINALIZADA', 'FINALIZADA')], default='CLASES NORMALES', max_length=30),
        ),
    ]
