# Generated by Django 6.0.2 on 2026-03-11 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_inventario'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='observacion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
