# Generated by Django 6.0.2 on 2026-02-19 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_reserva_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratorio',
            name='correo_responsable',
            field=models.CharField(default='innovacion@ucacue.edu.ec', max_length=100),
        ),
        migrations.AddField(
            model_name='laboratorio',
            name='numero_responsable',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('ACTIVA', 'ACTIVA'), ('EN REVISION', 'EN REVISION'), ('CANCELADA', 'CANCELADA'), ('FINALIZADA', 'FINALIZADA'), ('BLOQUEADA', 'BLOQUEADA'), ('ESTUDIANTIL', 'ESTUDIANTIL')], default='EN REVISION', max_length=20),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='tipo',
            field=models.CharField(choices=[('INDUCCION DOCENTE', 'INDUCCION DOCENTE'), ('INDUCCION ESTUDIANTIL', 'INDUCCION ESTUDIANTIL'), ('CLASES NORMALES', 'CLASES NORMALES')], default='CLASES NORMALES', max_length=30),
        ),
    ]
