# Generated by Django 6.0.2 on 2026-02-19 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_laboratorio_correo_responsable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estacion',
            name='modelo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
