# Generated by Django 6.0.2 on 2026-07-27 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_parametros_diseno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratorio',
            name='estado',
            field=models.CharField(choices=[('ACTIVO', 'ACTIVO'), ('INACTIVO', 'INACTIVO'), ('EN MANTENIMIENTO', 'EN MANTENIMIENTO'), ('RESTRINGIDO', 'RESTRINGIDO')], default='ACTIVO', max_length=20),
        ),
    ]
